version: '2'

services:
  authentication_database:
    image: postgres
    environment:
      - POSTGRES_USER=${GUILD_USER}
      - POSTGRES_PASSWORD=${GUILD_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - ./guild_db-data:/var/lib/postgresql/data/
    container_name: users_guild
  authentication_server:
    image: divieon/cerbrus
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgress=Server=authentication_database;Port=5432;User Id=${GUILD_USER};Password=${GUILD_PASSWORD};Database=AspIdUsers
    depends_on:
      - authentication_database
    ports:
      - 5001:80
    container_name: cerbrus


volumes:
  guild_db-data: