version: '3'

services:
  authentication_database:
    image: postgres
    environment:
      - POSTGRES_USER=${GUILD_USER}
      - POSTGRES_PASSWORD=${GUILD_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - ./guild_db-data:/var/lib/postgresql/data/
    container_name: users_guild
    
  authentication_server:
    image: divieon/homelab-identity-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT:5002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__PATH=/https/auth-server.pfx
      - ConnectionStrings__Postgress=Server=authentication_database;Port=5432;User Id=${GUILD_USER};Password=${GUILD_PASSWORD};Database=AspIdUsers

    depends_on:
      - authentication_database
    container_name: cerbrus
    ports:
      - 5001:80
      - 5002:443
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/https:ro
volumes:
  guild_db-data:
  certs:
